name: master

on:
  push: 
    branches: [master]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      - name: set up JDK 1.8
        uses: actions/setup-java@v2
        with:
          java-version: 17
          distribution: zulu

      # Execute unit tests
      - name: Unit Test
        run: ./gradlew testDebugUnitTest

      - name: Android Test Report
        uses: asadmansr/android-test-report-action@v1.2.0
        if: ${{ always() }} # IMPORTANT: run Android Test Report regardless

  build-apk:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Check Style
      uses: nikitasavinov/checkstyle-action@master
      with:
        checkstyle_config: google_checks.xml
        tool_name: Java Checkstyle

    - name: Setup JDK
      uses: actions/setup-java@v1
      with:
        java-version: 1.11

    # Build the APK
    - name: Build APK
      run: bash ./gradlew assembleDebug --stacktrace
    
    # Upload the created APK
    - name: Upload APK
      uses: actions/upload-artifact@v1
      with:
        name: apk
        path: app/build/outputs/apk/debug/app-debug.apk

  release-apk:
    runs-on: ubuntu-latest
    needs: build-apk

    steps:
    # Download the previously built APK
    - name: Download APK from build
      uses: actions/download-artifact@v1
      with:
        name: apk
    
    # Create a release with specified Tag name
    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.run_number }}
        release_name: Release APK
    
    # Upload the APK to a release
    - name: Upload Release APK
      id: upload_release_asset
      uses: actions/upload-release-asset@v1.0.1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: apk/app-debug.apk
        asset_name: AppName.apk
        asset_content_type: application/zip
